module operators();
    reg[4:0]a,b;
    reg[16:0]y;
    reg[16:0]y0;
    reg[16:0]y1;
    wire[10:0]x;
    reg s;
    assign x=(s==1)?a:b;
    initial 
        begin
      $display("1]ARTHEMETIC OPERATOR-----------");
        a=8; b=2;
        y=a+b;
        $display("Addition %d",y);
        y=a-b;
        $display("Subtraction %d",y);
        y=a*b;
        $display("Multiplication %d",y);
        y=a/b;
        $display("Division %d",y);
        y=a%b;
        $display("Modulus %d",y);
        y=a**b;
        $display("Power %d",y);
        $display("-------------------------------------------------------------------");

        $display("2]LOGICAL OPERATORS-----------------------------");
        y=a&&b;
        $display("Logical And %d",y);
        y=a||b;
        $display("Logival Or %d",y);
        y0=!a;
        $display("Logical Not of a %d",y0);
        y1=!b;
        $display("Logical Not of b %d",y1);    
        $display("--------------------------------------------------------------------");
        $display("3]RELATIONAL OPERATOR----------------------------");
        y=a>b;
        $display("Grater Than %d",y);
        y=a<b;
        $display("Less Than %d",y);
        y=a<=b;
        $display("Less Than Equal %d",y);
        y=a>=b;
        $display("Greater Than Equal %d",y1);
        $display("-----------------------------------------------------------------------");
        $display("4]Equality operator----------------------------------");
        y=a==b;
        $display("Logical Equal To %b",y);
        y=a!=b;
        $display("Logical Not Equal to %b",y);
        y=a===b;
        $display("Case Equal To %b",y);
        y=a!==b;
        $display("Case not equal to %b",y1);
        $display("-----------------------------------------------------------------------");

        $display("5]BITWISE OPERATOR-----------------------------------------------");
        y=a&b;
        $display("bitwise And %b",y);
        y=a|b;
        $display("Bitwise Or %b",y);
        y=~a;
        $display("Bitwise Not %b",y);
        y=~(a&b);
        $display("Bitwise Nand %b",y);
        y=~(a|b);
        $display("Bitwise Nor %b",y);
        y=a^b;
        $display("Bitwise Xor %b",y);
        y=~(a^b);
        $display("Bitwise Xnor %b",y);
        $display("------------------------------------------------------------------------");
        $display("6]REDUCTION OPERATOR");
        y=&b;
        $display("REDUCTION bitwise And %b",y);
        y=|b;
        $display("REDUCTION Bitwise Or %b",y);
        y=~a;
        $display("REDUCTION Bitwise Not %b",y);
        y=~(&b);
        $display("REDUCTION Bitwise Nand %b",y);
        y=~(|b);
        $display("REDUCTION Bitwise Nor %b",y);
        y=^b;
        $display("REDUCTION Bitwise Xor %b",y);
        y=~(^b);
        $display("REDUCTION Bitwise Xnor %b",y);
        $display("--------------------------------------------------------------------------");
        $display("7]SHIFTING OPERATOR------------------------------------------------");
        y=a<<1;
        $display("Logical Left Shift %b",y);
        y=a>>1;
        $display("Logical Right Shift %b",y);
        y=a<<<2;
        $display("Arthenetic Left Shift %b",y);
        $display(y);
        y=a>>>2;
        $display("Arthemetic Right Shift %b",y);
        $display("-----------------------------------------------------------------------------");
        $display("8]CONDITIONAL OR TURNARY OPERATOR-------------------------------------");
        s=1;#10;
        y=(s==1)?a:b;
        $display("2to1 mux a=0%d b=%0d y=%0d x=%0d",a,b,y,x);
        s=0;#10
        y=(s==1)?a:b;
        $display("2to1 mux a=0%d b=%0d y=%0d x=%0d",a,b,y,x);
        $display("-----------------------------------------------------------------------------");
        $display("9]CONCATENATION--------------------------------------------------------");
        y={a,b,a,b};
        $display("Concatenation of a=%b b=%b y=%b",a,b,y);
        y={a[7:0],b[7:0]};
        $display("Concatenation of a=%b b=%b y=%b",a,b,y);
        $display("------------------------------------------------------------------------------");
        $display("10]REPLICATION----------------------------------------------------------");
        y={{a[3:1],b[3:1],a[3:1],b[3:1]}};
        $display("Replication of Concatination a=%b b=%b y=%b",a,b,y);
        end   
        endmodule
